### ISSUE TITLE
Provider config variable `adminApiKey` is obsolete

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-newrelic#484]
### What happened?

The Pulumi New Relic provider has a config option called `adminApiKey`. However, the upsteam Terraform provider has no such option (at least [in the docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs)). I even went back a major version and did not see such an option in provider config.

I'm working on a New Relic workshop, and my code appears to work fine by only specifying `accountId` and `apiKey`, so this leads me to believe `adminApiKey` is obsolete. It's also very confusing because there is no description for what it's even _supposed_ to represent: not on [Installation and Configuration](https://www.pulumi.com/registry/packages/newrelic/installation-configuration/) and not on [the provider's API docs page](https://www.pulumi.com/registry/packages/newrelic/api-docs/provider/).

### Expected Behavior

n/a

### Steps to reproduce

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @jkodroff - thank you for filing this! We'll clean this up as soon as we can.

I verified with the NewRelic documentation that this key is in fact deprecated since 2020.

https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#key-details --> "Other API Keys"

**Comment by jkodroff** [comment]
@guineveresaenger Note that the registry docs will also have to be updated for the Install and Config page: https://www.pulumi.com/registry/packages/newrelic/installation-configuration/

**Comment by desteves** [comment]
Upvoting as we have another upcoming New Relic workshop and would be great to have this addressed by then (October 2024)

**Comment by jkodroff** [comment]
Still broken: 

<img width="781" height="450" alt="Image" src="https://github.com/user-attachments/assets/b49fd2b2-d8a4-473c-b39f-f8df0eb62bef" />
